start on started lab126_gui
stop on stopping lab126_gui

pre-start script
    . /etc/upstart/functions

    if [ -x /mnt/us/extensions/onlinescreensaver/bin/scheduler.sh ]; then
        /bin/sh /mnt/us/extensions/onlinescreensaver/bin/scheduler.sh &
    fi

    true
end script

post-stop script
    PID=`ps xa | grep "/bin/sh /mnt/us/extensions/onlinescreensaver/bin/scheduler.sh" | grep -v grep | awk '{ print $1 }'`
    [ -z "$PID" ] || kill $PID || true
end script
